-- 코드를 입력하세요
WITH T AS(SELECT FOOD_TYPE,	REST_ID,	REST_NAME,	FAVORITES, DENSE_RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK FROM REST_INFO  )
SELECT FOOD_TYPE,	REST_ID,	REST_NAME,	FAVORITES FROM T WHERE RNK=1 ORDER BY FOOD_TYPE DESC;
