-- 코드를 작성해주세요
WITH T AS (SELECT ID,SIZE_OF_COLONY, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC)AS SIZE FROM ECOLI_DATA)
SELECT ID, CASE WHEN SIZE=4 THEN 'LOW' WHEN SIZE=3 THEN 'MEDIUM' WHEN SIZE=2 THEN 'HIGH' ELSE 'CRITICAL' END AS COLONY_NAME FROM T ORDER BY ID;