WITH RENT AS (
    SELECT 
        H.HISTORY_ID, 
        C.CAR_TYPE, 
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    R.HISTORY_ID, 
    FLOOR(
        R.DAILY_FEE 
        * R.DAYS 
        * (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM RENT R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON R.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE = CASE
        WHEN R.DAYS >= 90 THEN '90일 이상'
        WHEN R.DAYS >= 30 THEN '30일 이상'
        WHEN R.DAYS >= 7 THEN '7일 이상'
    END
ORDER BY FEE DESC, R.HISTORY_ID DESC;