-- 코드를 작성해주세요
WITH CODE AS(
SELECT SUM(CODE)AS FCODE FROM SKILLCODES WHERE CATEGORY='Front End'
)
SELECT D.ID, D.EMAIL, D.FIRST_NAME,D.LAST_NAME
FROM DEVELOPERS D
CROSS JOIN CODE C
WHERE (D.SKILL_CODE & C.FCODE) > 0
ORDER BY D.ID;