-- 코드를 입력하세요
SELECT P.CATEGORY, T.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN (SELECT CATEGORY, MAX(PRICE)AS MAX_PRICE 
FROM FOOD_PRODUCT 
GROUP BY CATEGORY HAVING CATEGORY IN ('과자', '국', '김치', '식용유')) T
ON P.CATEGORY=T.CATEGORY AND T.MAX_PRICE=P.PRICE
ORDER BY  T.MAX_PRICE DESC;