WITH CODES AS (
    SELECT
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FRONT_CODE,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS PYTHON_CODE,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS CSHARP_CODE
)

SELECT GRADE, ID, EMAIL
FROM (
    SELECT
        CASE
            WHEN (D.SKILL_CODE & C.FRONT_CODE) > 0 
            AND (D.SKILL_CODE & C.PYTHON_CODE)  > 0 THEN 'A'
            WHEN (D.SKILL_CODE & C.CSHARP_CODE) >0 THEN 'B'
            WHEN (D.SKILL_CODE & C.FRONT_CODE) > 0  THEN 'C'
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS D
    CROSS JOIN CODES C
) T
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;